
[permanent]
/openai-chat-for-gamedev = "/ru/posts/openai-chat-for-gamedev"
/change-of-perception-of-complexity = "/ru/posts/change-of-perception-of-complexity"
/the-game-community-from-the-point-of-view-of-an-independent-game-developer = "/ru/posts/the-game-community-from-the-point-of-view-of-an-independent-game-developer"
/rpg-of-winning-marketing = "/ru/posts/rpg-of-winning-marketing"
/two-examples-of-overengineering-from-fastapi = "/ru/posts/two-examples-of-overengineering-from-fastapi"
/gamedev-sites = "/ru/posts/gamedev-sites"
/python-types-are-not-great = "/ru/posts/python-types-are-not-great"
/6-s191-introduction-to-deep-learnin = "/ru/posts/6-s191-introduction-to-deep-learnin"
/intelligence-competency-and-decision-making = "/ru/posts/intelligence-competency-and-decision-making"
/about-backend-migrations = "/ru/posts/about-backend-migrations"
/about-system-thinking = "/ru/posts/about-system-thinking"
/life-and-work-with-models = "/ru/posts/life-and-work-with-models"
/results-of-2020-for-me-and-the-blog = "/ru/posts/results-of-2020-for-me-and-the-blog"
/about-blog = "/ru/posts/about-blog"
/turn-on-donate = "/ru/posts/turn-on-donate"
/using-dall-e-3-for-gamedev = "/ru/posts/using-dall-e-3-for-gamedev"
/let-sell-work-of-players = "/ru/posts/let-sell-work-of-players"
/agreement-on-shares = "/ru/posts/agreement-on-shares"
/notes-on-vr-and-oculus-quest-2 = "/ru/posts/notes-on-vr-and-oculus-quest-2"
/cooks-first-around-the-world-deaths = "/ru/posts/cooks-first-around-the-world-deaths"
/about-book-invention-of-science = "/ru/posts/about-book-invention-of-science"
/i-am-a-person-who = "/ru/posts/i-am-a-person-who"
/apple-combo-bug = "/ru/posts/apple-combo-bug"
/morphologic-is-open-source = "/ru/posts/morphologic-is-open-source"
/non-consumable-purchases = "/ru/posts/non-consumable-purchases"
/about-book-methodology-of-scientific-knowledge = "/ru/posts/about-book-methodology-of-scientific-knowledge"
/how-to-beginner-choose-a-database = "/ru/posts/how-to-beginner-choose-a-database"
/experience-of-devgamm-spring-2021 = "/ru/posts/experience-of-devgamm-spring-2021"
/about-book-people-like-gods = "/ru/posts/about-book-people-like-gods"
/graphql-and-python = "/ru/posts/graphql-and-python"
/the-significance-of-the-event-in-the-mmo = "/ru/posts/the-significance-of-the-event-in-the-mmo"
/python-hypothesis = "/ru/posts/python-hypothesis"
/community-and-conceptual-integrity = "/ru/posts/community-and-conceptual-integrity"
/generative-adversarial-network-implementation = "/ru/posts/generative-adversarial-network-implementation"
/scold-or-praise-me = "/ru/posts/scold-or-praise-me"
/formalism-injury = "/ru/posts/formalism-injury"
/experiments-with-tarantoga-completed = "/ru/posts/experiments-with-tarantoga-completed"
/one-form-two-products = "/ru/posts/one-form-two-products"
/redundancy-of-knowledge-and-their-evolution = "/ru/posts/redundancy-of-knowledge-and-their-evolution"
/what-to-read-to-code-better = "/ru/posts/what-to-read-to-code-better"
/julia-experience = "/ru/posts/julia-experience"
/exocortex-minimal-functionality = "/ru/posts/exocortex-minimal-functionality"
/minidrama-python-c-rust-cryptography-and-gentoo = "/ru/posts/minidrama-python-c-rust-cryptography-and-gentoo"
/how-i-did-and-would-do-gdpr-support = "/ru/posts/how-i-did-and-would-do-gdpr-support"
/automatic-imports-in-python = "/ru/posts/automatic-imports-in-python"
/notes-about-containerization = "/ru/posts/notes-about-containerization"
/concept-document-news-makers = "/ru/posts/concept-document-news-makers"
/about-book-psychology-and-space = "/ru/posts/about-book-psychology-and-space"
/trendy-typing-in-python = "/ru/posts/trendy-typing-in-python"
/why-developers-do-not-make-this-simple-thing = "/ru/posts/why-developers-do-not-make-this-simple-thing"
/drafting-class-franchise = "/ru/posts/drafting-class-franchise"
/squirrel-eiserloh-gdc-videos = "/ru/posts/squirrel-eiserloh-gdc-videos"
/me-and-the-smart-gui-in-ide = "/ru/posts/me-and-the-smart-gui-in-ide"
/you-cant-just-take-and-run-dl = "/ru/posts/you-cant-just-take-and-run-dl"
/procedural-generation-to-the-masses = "/ru/posts/procedural-generation-to-the-masses"
/the-diamond-age-or-a-young-ladys-illustrated-primer = "/ru/posts/the-diamond-age-or-a-young-ladys-illustrated-primer"
/interesting-articles-rss = "/ru/posts/interesting-articles-rss"
/explaining-religion = "/ru/posts/explaining-religion"
/tests-that-test-tests = "/ru/posts/tests-that-test-tests"
/statistics-and-cats = "/ru/posts/statistics-and-cats"
/ai-will-not-or-will-replace-us-all = "/ru/posts/ai-will-not-or-will-replace-us-all"
/results-of-2021-for-me-and-the-blog = "/ru/posts/results-of-2021-for-me-and-the-blog"
/silly-predictions-about-artificial-intelligence = "/ru/posts/silly-predictions-about-artificial-intelligence"
/the-results-of-the-sabbatical-2019-2021 = "/ru/posts/the-results-of-the-sabbatical-2019-2021"
/the-hacker-ethic-and-the-spirit-of-the-information-age = "/ru/posts/the-hacker-ethic-and-the-spirit-of-the-information-age"
/how-to-teach-and-not-teach-math = "/ru/posts/how-to-teach-and-not-teach-math"
/why-do-i-need-a-plan = "/ru/posts/why-do-i-need-a-plan"
/systems-thinking-in-practice = "/ru/posts/systems-thinking-in-practice"
/kaggle-digit-recognizer-solution = "/ru/posts/kaggle-digit-recognizer-solution"
/ontogenesis-from-cell-to-human = "/ru/posts/ontogenesis-from-cell-to-human"
/time-money-fun-in-mmo = "/ru/posts/time-money-fun-in-mmo"
/business-on-own-money = "/ru/posts/business-on-own-money"
/why-i-dont-like-rust = "/ru/posts/why-i-dont-like-rust"
/game-topology = "/ru/posts/game-topology"
/making-ai-tamagotchi-with-chatgpt = "/ru/posts/making-ai-tamagotchi-with-chatgpt"
/the-truth-is-out-there = "/ru/posts/the-truth-is-out-there"
/evil-samaritans = "/ru/posts/evil-samaritans"
/talking-man = "/ru/posts/talking-man"
/morphological-analysis-prototype = "/ru/posts/morphological-analysis-prototype"
/russian-text-generation = "/ru/posts/russian-text-generation"
/unique-identifiers-for-source-connection = "/ru/posts/unique-identifiers-for-source-connection"
/the-tale-concept-document = "/ru/posts/the-tale-concept-document"
/ethics-of-knowledge-transfer = "/ru/posts/ethics-of-knowledge-transfer"
/python-3-types-in-the-wild = "/ru/posts/python-3-types-in-the-wild"
/learn-right = "/ru/posts/learn-right"
/anti-cheating-ethics = "/ru/posts/anti-cheating-ethics"
/life-by-subscription = "/ru/posts/life-by-subscription"
/concept-document-for-the-game-tales = "/ru/posts/concept-document-for-the-game-tales"
/конспект-по-статистике = "/ru/posts/abstract-on-statistics"
/abstract-on-statistics = "/ru/posts/abstract-on-statistics"
/when-it-is-necessary-to-listen-to-users = "/ru/posts/when-it-is-necessary-to-listen-to-users"
/mathematicians-got-to-neural-networks = "/ru/posts/mathematicians-got-to-neural-networks"
/feature-programming = "/ru/posts/feature-programming"
/about-book-the-world-until-yesterday = "/ru/posts/about-book-the-world-until-yesterday"
/google-become-visionary-sponsor-for-python = "/ru/posts/google-become-visionary-sponsor-for-python"
/concept-document-for-the-game-s-space-opera-engine = "/ru/posts/concept-document-for-the-game-s-space-opera-engine"
/my-mmog-vision = "/ru/posts/my-mmog-vision"
/monopolization-of-machine-learning = "/ru/posts/monopolization-of-machine-learning"
/internet-and-vat = "/ru/posts/internet-and-vat"
/theft-of-test-task-results = "/ru/posts/theft-of-test-task-results"
/collect-metrics-in-linux = "/ru/posts/collect-metrics-in-linux"
/exocortex-metainformation = "/ru/posts/exocortex-metainformation"
/about-worlds-building = "/ru/posts/about-worlds-building"
/devby-social-research = "/ru/posts/devby-social-research"
/about-book-wtf = "/ru/posts/about-book-wtf"
/russian-language-gpt-3-from-sber-vs-the-tale = "/ru/posts/russian-language-gpt-3-from-sber-vs-the-tale"
/tarantoga-second-pancake = "/ru/posts/tarantoga-second-pancake"
/devops-tasks = "/ru/posts/devops-tasks"
/simply-on-the-relationship-between-linear-algebra-and-neural-networks = "/ru/posts/simply-on-the-relationship-between-linear-algebra-and-neural-networks"
/about-book-harry-potter-and-the-methods-of-rationality = "/ru/posts/about-book-harry-potter-and-the-methods-of-rationality"
/future-of-content-in-gamedev = "/ru/posts/future-of-content-in-gamedev"
/fictional-universe-setting-work-what-the-difference = "/ru/posts/fictional-universe-setting-work-what-the-difference"
/will-as-an-artifact-of-the-model-of-reality = "/ru/posts/will-as-an-artifact-of-the-model-of-reality"
/life-and-work-with-mistakes = "/ru/posts/life-and-work-with-mistakes"
/about-basic-income = "/ru/posts/about-basic-income"
/who-is-in-charge = "/ru/posts/who-is-in-charge"
/business-evangelist = "/ru/posts/business-evangelist"
/python-and-openapi = "/ru/posts/python-and-openapi"
/links-to-courses-on-machine-learning-and-deep-learning = "/ru/posts/links-to-courses-on-machine-learning-and-deep-learning"
/yet-another-tarantoga = "/ru/posts/yet-another-tarantoga"
/about-resource-gathering-mechanics = "/ru/posts/about-resource-gathering-mechanics"
/backend-migrations-in-practice = "/ru/posts/backend-migrations-in-practice"
/dungeon-generation-from-simple-to-complex = "/ru/posts/dungeon-generation-from-simple-to-complex"
/cooks-first-around-the-world-context = "/ru/posts/cooks-first-around-the-world-context"
/cooks-first-around-the-world-shipwreck = "/ru/posts/cooks-first-around-the-world-shipwreck"
/porting-the-tale-from-python-2-to-python-3 = "/ru/posts/porting-the-tale-from-python-2-to-python-3"
/cooks-first-around-the-world-interesting-facts = "/ru/posts/cooks-first-around-the-world-interesting-facts"
/summa-technologiae = "/ru/posts/summa-technologiae"
/nn-anime-avatars-generator = "/ru/posts/nn-anime-avatars-generator"
/composition-vs-classification = "/ru/posts/composition-vs-classification"
/cooks-first-around-the-world-politics = "/ru/posts/cooks-first-around-the-world-politics"
/resource-model-of-the-game-resources = "/ru/posts/resource-model-of-the-game-resources"
/my-view-on-nft = "/ru/posts/my-view-on-nft"
/signed-the-letter-in-support-of-stallman = "/ru/posts/signed-the-letter-in-support-of-stallman"
/susanna-clarke-books = "/ru/posts/susanna-clarke-books"
/history-of-organizational-theory = "/ru/posts/history-of-organizational-theory"
/repair-of-complex-systems = "/ru/posts/repair-of-complex-systems"
/tarantoga-data-model = "/ru/posts/tarantoga-data-model"
/gamedev-resume-notes = "/ru/posts/gamedev-resume-notes"
/anti-utopia-of-science = "/ru/posts/anti-utopia-of-science"
/two-years-writing-rfc-statistics = "/ru/posts/two-years-writing-rfc-statistics"
/julia-is-next-python = "/ru/posts/julia-is-next-python"
/update-emacs-configs = "/ru/posts/update-emacs-configs"
/budapest-baths-goulash-chimney-cakes = "/ru/posts/budapest-baths-goulash-chimney-cakes"
/what-happens-if-you-open-the-code-of-your-game = "/ru/posts/what-happens-if-you-open-the-code-of-your-game"
/testing-semantic-of-code = "/ru/posts/testing-semantic-of-code"
/about-book-system-thinking-2019 = "/ru/posts/about-book-system-thinking-2019"
/about-book-freakonomics = "/ru/posts/about-book-freakonomics"
/exocortex-3-5 = "/ru/posts/exocortex-3-5"
/looking-for-a-job-2021 = "/ru/posts/looking-for-a-job-2021"
/genes-memes-memeplexes = "/ru/posts/genes-memes-memeplexes"
/first-look-at-latex = "/ru/posts/first-look-at-latex"
/future-of-mmorpg = "/ru/posts/future-of-mmorpg"
/business-like-a-game = "/ru/posts/business-like-a-game"
/rip-miura-berserk-finished = "/ru/posts/rip-miura-berserk-finished"
/concept-document-of-board-role-playing-mmo-game-show = "/ru/posts/concept-document-of-board-role-playing-mmo-game-show"
/cooks-first-around-the-world-natives = "/ru/posts/cooks-first-around-the-world-natives"
/making-a-fictional-universe-month-1 = "/ru/posts/making-a-fictional-universe-month-1"
/using-dall-e-for-gamedev = "/ru/posts/using-dall-e-for-gamedev"
/feeds-fun-news-reader-with-tags-and-chatgpt = "/ru/posts/feeds-fun-news-reader-with-tags-and-chatgpt"
/tarantoga-the-first-pancake = "/ru/posts/tarantoga-the-first-pancake"
/automatic-quests-generator = "/ru/posts/automatic-quests-generator"
/my-exocortex = "/ru/posts/my-exocortex"
/about-book-powerful = "/ru/posts/about-book-powerful"
/how-to-choose-a-university-and-specialty = "/ru/posts/how-to-choose-a-university-and-specialty"
/about-book-self-comes-to-mind = "/ru/posts/about-book-self-comes-to-mind"
/write-your-own-adventure = "/ru/posts/write-your-own-adventure"
/concept-document-for-the-game-swarm = "/ru/posts/concept-document-for-the-game-swarm"
/about-book-art-of-war = "/ru/posts/about-book-art-of-war"
/blood-sweat-and-pixels = "/ru/posts/blood-sweat-and-pixels"
/open-source-authentication-services = "/ru/posts/open-source-authentication-services"
/about-names-creation = "/ru/posts/about-names-creation"
/thoughts-on-programming-languages = "/ru/posts/thoughts-on-programming-languages"
/making-a-fictional-universe-month-2 = "/ru/posts/making-a-fictional-universe-month-2"
/bots-and-twinks-in-games = "/ru/posts/bots-and-twinks-in-games"
/how-to-fail-interview-with-me = "/ru/posts/how-to-fail-interview-with-me"
/concept-document-nocraft = "/ru/posts/concept-document-nocraft"
/organization-of-information = "/ru/posts/organization-of-information"
/pokemon-go = "/ru/posts/pokemon-go"
/about-it-progress-and-lack-of-specialists = "/ru/posts/about-it-progress-and-lack-of-specialists"
/results-of-2023-for-me-and-the-blog = "/ru/posts/results-of-2023-for-me-and-the-blog"
/forecast-for-2050 = "/ru/posts/forecast-for-2050"
/looking-for-people-to-join-the-team = "/ru/posts/looking-for-people-to-join-the-team"
/verification-with-special-cases = "/ru/posts/verification-with-special-cases"
/the-tale-map-history-till-february-2020 = "/ru/posts/the-tale-map-history-till-february-2020"
/space-of-mmo-mechanics = "/ru/posts/space-of-mmo-mechanics"
/flow-psychology-of-optimal-experience = "/ru/posts/flow-psychology-of-optimal-experience"
/about-the-degradation-of-fun = "/ru/posts/about-the-degradation-of-fun"
/the-hero-with-a-thousand-faces = "/ru/posts/the-hero-with-a-thousand-faces"
/illusion-of-knowledge = "/ru/posts/illusion-of-knowledge"
/neurocopywriting = "/ru/posts/neurocopywriting"
/how-to-design-a-dungeon = "/ru/posts/how-to-design-a-dungeon"
/rome-bustling-renovation-scammers = "/ru/posts/rome-bustling-renovation-scammers"
/tarantoga-memeplexes = "/ru/posts/tarantoga-memeplexes"
/results-of-2022-for-me-and-the-blog = "/ru/posts/results-of-2022-for-me-and-the-blog"
/about-the-dismissal-of-sam-altman-and-regulation-of-ai = "/ru/posts/about-the-dismissal-of-sam-altman-and-regulation-of-ai"
/next-gamedesign-frontier = "/ru/posts/next-gamedesign-frontier"
/paul-graham-superlinear-returns = "/ru/posts/paul-graham-superlinear-returns"
/new-articles-newsletter = "/ru/posts/new-articles-newsletter"
/verification-though-logic-duplication = "/ru/posts/verification-though-logic-duplication"
/about-symbols = "/ru/posts/about-symbols"
/scale = "/ru/posts/scale"
/mmozg-hot-tea-podcast = "/ru/posts/mmozg-hot-tea-podcast"
/thinking-through-writing = "/ru/posts/thinking-through-writing"
/the-logic-of-chance = "/ru/posts/the-logic-of-chance"
/about-book-gamedesign = "/ru/posts/about-book-gamedesign"
/how-do-i-learn-history = "/ru/posts/how-do-i-learn-history"
/few-words-about-github-copilot = "/ru/posts/few-words-about-github-copilot"
/telegram-channel = "/ru/posts/telegram-channel"
/infinity-of-data-schemas = "/ru/posts/infinity-of-data-schemas"
/pydicates-predicates-for-python = "/ru/posts/pydicates-predicates-for-python"
/more-news-on-procedural-generation = "/ru/posts/more-news-on-procedural-generation"
/projects = "/ru/posts/projects"
/topics = "/ru/posts/"
/about = "/ru/posts/about"
/contents = "/ru/posts/best"
/webdev = "/ru/posts/webdev"
/feed = "/ru/feeds/atom"
/making-a-fictional-universe-month-quantity-survey = "/ru/posts/making-a-fictional-universe-month-quantity-survey"
/discord-server-for-blog-and-communication-with-you = "/ru/posts/discord-server-for-blog-and-communication-with-you"

# redirects to cv
"/ru/cv" = "https://tiendil-curriculum-vitae.s3.eu-central-1.amazonaws.com/cv_alexey_yeletski_ru.pdf"
"/en/cv" = "https://tiendil-curriculum-vitae.s3.eu-central-1.amazonaws.com/cv_aliaksei_yaletski_en.pdf"

# new redirects
"/ru/posts/making-a-fictional-universe-month-quantity-survey" = "/ru/posts/making-a-fictional-universe-quantity-survey"