title = "Эмерджентный Блог"
subtitle = "Эссе о разработке игр, мышлении и книгах"
author = "Елецкий Алексей (Tiendil)"

[[menu]]
  type = "article"
  name = "Обо мне"
  slug = 'about'

[[menu]]
  type = "blog"
  name = "Блог"

[[menu]]
  type = "article"
  name = "Лучшее"
  slug = "best"

[[menu]]
  type = "article"
  name = "Проекты"
  slug = "projects"

[[menu]]
  type = "article"
  name = "MCP"
  slug = "mcp"

[[menu]]
  type = "feed"
  css_classes = "ti ti-rss"
  name = ""
  tooltip = "Лента новостей"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-telegram"
  name = ""
  tooltip = "Telegram канал"
  url = "https://t.me/tiendil_org_ru"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-twitter"
  name = ""
  tooltip = "Twitter"
  url = "https://x.com/tiendil_org"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-bluesky"
  name = ""
  tooltip = "Bluesky"
  url = "https://bsky.app/profile/tiendil.bsky.social"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-github"
  name = ""
  tooltip = "GitHub профиль"
  url = "https://github.com/Tiendil"

[license]
url = "http://creativecommons.org/licenses/by-nc-nd/4.0/"
name = "CC BY-NC-ND 4.0"

[tags_translations]
theory = "теория"
practice = "практика"
development = "разработка"
gamedev = "разработка игр"
society = "общество"
books = "книги"
game-design = "дизайн игр"
thinking = "мышление"
futurology = "футурология"
evolution = "эволюция"
open-source = "open source"
python = "Python"
monetization = "монетизация"
neural-networks = "нейронные сети"
business = "бизнес"
systems = "системы"
the-tale = "the-tale.org"
state = "государство"
economics = "экономика"
procedural-content-generation = "процедурная генерация"
reflection = "рефлексия"
mmo = "ММО"
psychology = "психология"
exocortex = "экзокортекс"
backend = "бэкенд"
education = "образование"
tarantoga = "Тарантога"
tarantoga-development = "разработка Тарантоги"
blog = "блог"
concepts = "концепты"
tests = "тесты"
habrahabr = "habr.ru"
rust = "Rust"
julia = "Julia"
jupyter-notebooks = "ноутбуки Jupyter"
movies = "фильмы"
geography = "география"
feeds-fun = "feeds.fun"
interesting = "интересные посты"
best = "лучшие посты"
world-builders = "World Builders"
games = "игры"
biology = "биология"
world-design = "дизайн миров"
prompt-engineering = "prompt engineering"
tutorial = "урок"
podcasts = "подкасты"
ai-notes-2024 = "Заметки об ИИ в 2024"
cooks-first-around-the-world = "Первая кругосветка Кука"
world-builders-2023 = "World Builders 2023"
dive-into-deep-learning = "Погружение в глубокое обучение"
databases = "базы данных"
fiction-books = "художественные книги"
professional-books = "профессиональные книги"
popular-science-books = "научно-популярные книги"
popular-philosophy-books = "философско-популярные книги"
history-books = "исторические книги"
results-of-the-year = "итоги года"
scientific-papers = "научные статьи"
management = "управление"
vantage-on-management = "взгляд на управление"
science = "наука"

# TODO: Maybe we need tag "engineering" in pair to "science" tag?
# But it will intersect significantly with "development" tag.
# Need to think about it.

[theme_translations]
tags_filter_header = 'Нашли эссе:'
last_posts_header = 'Последние эссе'
article_similar_header = 'Читать далее'
